version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./src/.
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    #command: ['sh', '-c', 'while true; do sleep 100; done']
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
